site_name: IT 정보 위키
site_description: IT 관련 다양한 정보를 정리한 정보 위키

theme:
  name: material
  language: ko
  palette:
    primary: 'blue'
    accent: 'light blue'
  features:
    - navigation.tabs
    - navigation.instant
    - search.highlight
    - search.suggest
  favicon: images/favicon.ico

nav:
  - 대문: index.md

  - 소프트웨어:
      - 개요: software/index.md
      - 운영체제:
          - 개요: software/os/index.md
          - Windows: software/os/windows/index.md
          - macOS: software/os/macos/index.md
          - Linux: software/os/linux/index.md
      - 시스템 소프트웨어:
          - 개요: software/system/index.md
      - 미들웨어:
          - 개요: software/middleware/index.md
      - 프로그램:
          - 개요: software/programs/index.md
          - 게임:
              - 개요: software/programs/games/index.md
              - Roblox:
                  - 개요: software/programs/games/roblox/index.md
                  - 작동 원리: software/programs/games/roblox/basics/how-roblox-works.md
          - 생산성 프로그램:
              - 개요: software/programs/productivity/index.md

  - 개발:
      - 개요: development/index.md
      - 프로그래밍 언어:
          - 개요: development/languages/index.md
      - 프레임워크:
          - 개요: development/frameworks/index.md

  - 데이터:
      - 개요: data/index.md
      - AI / ML: data/ai-ml.md
      - 빅데이터: data/bigdata.md
      - 데이터베이스:
          - 개요: data/database/index.md
          - MySQL: data/database/mysql.md

  - 보안:
      - 개요: security/index.md

  - 용어:
      - 개요: terminology/index.md

  - 작성 가이드:
      - 개요: writing-guide/index.md
      - 공통 템플릿: writing-guide/common-template.md

extra:
  generator: false

plugins:
  - search
